# Generated by Django 4.1.2 on 2022-10-26 04:41

import buyurtmaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmaapp', '0002_savat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='miqdor',
            field=models.PositiveSmallIntegerField(default=1, validators=[buyurtmaapp.models.validate_miqdor]),
        ),
    ]
