# Generated by Django 4.1.2 on 2022-10-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brend', models.CharField(max_length=20)),
                ('narx', models.FloatField()),
                ('batafsil', models.TextField()),
                ('kafolat', models.CharField(max_length=30)),
                ('yetkazish', models.CharField(max_length=20)),
                ('mavjud', models.BooleanField()),
                ('chegirma', models.FloatField(default=0)),
                ('ichki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.ichki')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='ichki_mahsulot')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot')),
            ],
        ),
    ]
